language: erlang

otp_release:
  - 20.3
  - 21.1

install:
  sudo pip install codecov

script:
  - rebar3 eunit
  - rebar3 ct
  - rebar3 dialyzer

after_success:
  - rebar3 coveralls send
  - make codecov

deploy:
  provider: script
  script: bash scripts/publish.sh
  on:
    tags: true

cache:
  directories:
    - $HOME/.cache/rebar3
